apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  namespace: default
  labels:
    name: my-nginx-pod 
    profile: dev
spec:
  containers:
  - name: my-nginx
    image: nginx
    ports:  
    - containerPort: 80